# Generated by Django 2.2.20 on 2021-09-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.IntegerField(default=0)),
                ('seller', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('bidamnt', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('document', models.ImageField(upload_to='property_details')),
                ('pic1', models.ImageField(upload_to='property_details')),
                ('pic2', models.ImageField(upload_to='property_details')),
                ('pic3', models.ImageField(upload_to='property_details')),
                ('pic4', models.ImageField(upload_to='property_details')),
            ],
        ),
    ]
