# Generated by Django 2.2.20 on 2021-09-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('home', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.seller'),
        ),
        migrations.AddField(
            model_name='bidder',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.credentials'),
        ),
    ]
